### ISSUE TITLE
Detection of the Chroma Keyboard

### ISSUE THREAD

**Issue by lah7** [lah7/razer_blackwidow_chroma_gui#10]
Currently no back-end code exists to detect the keyboard. I'm not too sure myself which way is best to address this... `lsusb` and identify IDs? Via daemon? Instead, just use this to check the DBUS service is running?

I have the page and images ready, just haven't committed them yet.

**Comment by terrycain** [comment]
Look at the bash scripts in `install_files/share`. Eventually I'll create some nice ones which work for multiple devices (as I now have the chroma keyboard mouse and mousemat)

Also in `/sys/bus/hid/drivers/razerkbd`there will be a symlink like `0003:1532:0203.0003` anything in that format is linked to the keyboard driver.

You can get the device type from a kernel file (don't even need root)
```
cat /sys/bus/hid/drivers/razerkbd/0003:1532:0203.0003/device_type
Razer BlackWidow Chroma
```

**Comment by lah7** [comment]
I've written a "framework" in 3f347bc17c92cd50e7f0d2e526d1d2d19932665e of how multiple devices in the program can be presented, but of course, it's just a placebo for now - nothing is detected.

I am thinking the daemon is being reworked to support multiple devices simultaneously?

**Comment by terrycain** [comment]
Eventually yes, to be all proper and that technically we should leave device discovery to the daemon.

**Comment by lah7** [comment]
Nearly forgot about #12, we best keep *multiple devices in GUI* discussions under that one.

I just remembered the original idea of this: A friendly error message to appear warning that no device was detected. Added in 45d4bd62d28c8f791c5f66a2d8ad5fea968d1596

**Comment by terrycain** [comment]
Well if the daemon isn't running display a message like can't contact razer service etc..., I've added a few more methods to the daemon's DBus interface, ill soon add them to the python razer lib, this means we can loop through the devices the daemon knows about and get information from them.

First things first, we need to split out all of the code from chroma_controller.py into separate files. chroma_controller should literally just display the window, other files then should care about the webpages inside of it. I also think we should refactor how JavaScript passes messages back to python, instead of splitting on `?` we could pass back JSON which we could then use python to convert it into a dictionary which would be much nicer (and it would do type conversion for us).
Finally we need to be careful on the order JavaScript is executed as that was the main issue the other day.

Once chroma_controller is nice, we can add support for all the currently supported devices. Primarily the chroma, but now we support the BlackWidow Ultimate 2013 & 2016, Razer Firefly and the Razer Mamba Chroma

**Comment by lah7** [comment]
A "failed to connect to dbus" message now appears, rather then silently exit with a terminal message. This message can now be more detailed now, like:
 * "No devices detected"
 * "Could not verify files for service, may not be properly installed" *(should a file existence check fail, indicating the user forgot to install)*

Everything up to this point is working perfectly well for the BlackWidow Chroma, we ought to start using tags ("releases" on GitHub?) to track version changes in case we need to fall back (or to reflect how fast the code has developed. :wink:)

Splitting the code (as with JS for each page) may be a good idea, we'll also need to refactor which device is "active", so the GUI / DBUS knows which device to send commands to.

----
As for JavaScript execution order, a rule of thumb is that:
 * `via file.js` = **Non-Python** dependent stuff - like setting UI buttons, layout of page, interactive functions for later, initial variables, etc.
 * `via Python` = **Python**-dependent stuff - like looping and setting keys in the profile editor and setting preferences after the page has *fully loaded*.

----
For the Ultimate variation, we can disable the RGB features and force green on all the keys, possibly noting which type of keyboard in the save file - so either:
 * Opening RGB profiles on the Ultimate variation keeps the RGB, but only shows green in the editor, making them compatible with the Chroma.
 *  **Or** opening RGB profiles for editing with a Ultimate variation loses RGB (set all to green).

---------
I won't be committing for a few days, so feel free to go ahead with your infrastructure changes. I'm here to test and ensure everything still works.

**Comment by terrycain** [comment]
> "failed to connect to dbus" mess...

That's good, yeah we can be informative about the errors etc... Could even drop them a link to documentation when its available. I agree we should start tagging releases, but all the developers need to agree ;). We should start making a check-list and milestones, so that once we reach a milestone we can then tag a release, but of course that means every one should work towards that and agree on the milestones etc...

> Splitting the code (as with JS for each page) may be a good idea, we'll also need to refactor which device is "active", so the GUI / DBUS knows which device to send commands to.

We technically don't need to worry about the active device too much as we can resort to just setting the active device before every call, that way it'll work even if something external to program changes the active device state. We should be able to call I think I named it `get_device` or `get_name` that will give us a string representation of the device name.

---

> As for JavaScript execution order, a rule of thumb is that:

It doesn't so much matter whether or not its ran from a script, but if the python runs JavaScript straight after it has asked a page to load, that has the opportunity to run before the jQuery document.ready function has run and technically before and HTML has been loaded. It's more of an issue here than on the web as load times here are sub-millisecond as well as the asynchronous nature of JavaScript.

---

> For the Ultimate variation, we can disable..

Yeah, haven't got custom colours for the 2016 working yet so we should keep that disabled but yes we could force green (and different shades of green), we'll also need to disable the macro keys for 2016 and add an effect called starlight. For the 2013 that can't address keys individually so preventing colour profiles would be good.

We need to decide on a save format for the profiles as they currently are just the raw binary that will set sent to the daemon. There are many options, we could opt for a binary format aka just serialise the profile class to a file, or we could output JSON but that would be slower but more human readable (and probably look quite ugly with all the RGB data in it.

**Comment by lah7** [comment]
> We need to decide on a save format for the profiles

I like the binary format currently for its speed, so preferably one that's fast from file -> memory -> daemon. In a way, using our own format is like re-inventing the wheel, since JSON is more open (readable) and would make it easy for external modifications. If we go with binary, some simple documentation would be a nice to add, just think if someone made a converter between Synapse's format :wink:

**Comment by terrycain** [comment]
Synapse format is in the cloud, whilst I *could* link our app with their web services, they probably wouldn't like that too much. I agree the binary format is nicer, and we don't exactly need external editing as worse case they can use the same python library we use.

I'll start thinking up some ideas. I am just debating whether or not to just serialise (pickle in python terms) the entire profile class, least that way when we de-serialise, it will just appear as the class.

**Comment by lah7** [comment]
I'm sure I saw Syanpse profile "files" from somewhere, I only looked at Syanpse once (bit bloaty, glad we have an "open source alternate" frontend for Linux)

Whichever one we opt for, we should try to aim for compatibility across versions (should future changes occur) since this would be a (possible) third time the profile format got changed, I haven't created my key profiles yet for that reason.

**Comment by terrycain** [comment]
I think serialisation would be cool but we would need to properly plan out the storage format so we don't keep changing it.
